#!/bin/bash


function usage(){

	printf "bash base32encode -s \"Hello world\"\n"
	printf "bash base32encode -f \"/home/user/filetoencode.txt\"\n"
	printf "Options:\n"
	printf "%s\n" "-s            Encode string"
	printf "%s\n" "-f            Encode file"
	exit

}

if [[ -z "$1" ]] || [[ -z "$2" ]]
then
	usage
fi


if [[ "$1" == "-s" ]]
then
	printf "\nEncoding string $2\n"
	printf "$2" | base32

fi

if [[ "$1" == "-f" ]]
then
	printf "\nEncoding file $2\n"
	cat "$2" | base32
fi
