#!/bin/bash

function usage(){

	printf "Usage\nbash octalencode -s \"Hello world\"\n"
        printf "bash octalencode -f \"/home/user/filetoencode.txt\"\n"
        printf "Options:\n"
        printf "%s\n" "-s            Encode string to octal"
        printf "%s\n" "-f            Encode file to octal"


}

if [[ -z "$1" ]] || [[ -z "$2" ]]
then
        usage
	exit
fi


if [[ "$1" == "-s" ]]
then
        printf "\nEncoding string $2 to octal\n"
        octal_encode_string=$(printf "$2" | od -b -An | tr -s " " | tr -t "\n" " " | tr -s " ")
	printf "$octal_encode_string"
fi


if [[ "$1" == "-f" ]]
then
        printf "\nEncoding file $2 to octal\n"
	octal_encode_file=$(cat "$2" | od -b -An | tr -s " " | tr -t "\n" " " | tr -s " ")
        printf "$octal_encode_file"
fi
