#!/bin/bash


function usage(){

	printf "bash base64decode -s \"Hello world\"\n"
	printf "bash base64decode -f \"/home/user/filetodecode.txt\"\n"
	printf "Valid for Base64 UTF-8 and Base64 WINDOWS UNICODE formats if you have pwsh installed\n"
	printf "Options:\n"
	printf "%s\n" "-s            Decode string"
	printf "%s\n" "-f            Decode file"
	exit

}


if [[ -z "$1" ]] || [[ -z "$2" ]]
then
	usage
fi


if [[ "$1" == "-s" ]]
then
	printf "\nDecoding string $2 Base64 UTF-8 format and windows unicode\n"
	printf "$2" | base64 -d
fi


if [[ "$1" == "-f" ]]
then
	printf "\nDecoding file $2 Base64 UTF-8 format and windows unicode\n"
	cat "$2" | base64 -d
fi
