#!/bin/bash

function info_findprivileges(){
	printf -- "#############################################\n"
        printf -- "# FIND SOME INTERESTING PRIVILEGES          #\n"
        printf -- "##########################################################\n"
        printf -- "# find / -user alice -type f 2>/dev/null                 #\n"
        printf -- "# find / -perm -u=s -type f 2>/dev/null                  #\n"
        printf -- "#--------------------------------------------------------#\n"
        printf -- "# find /etc -name passwd -print 2>/dev/null              #\n"
        printf -- "# find / -type f -readable 2>/dev/null | grep README.txt #\n"
        printf -- "##########################################################\n"

}

info_findprivileges
